#ifndef PARAMS_H
#define PARAMS_H

#define SC_EPSILON_MED 1E-5
#define SC_EPSILON_SMALL 1E-12
#define BIG_M 1E20

enum STATUS
{
    SC_SUCCESFULL,
    SC_GENERIC_ERROR,
    SC_SOLVER_NOT_FOUND,
    SC_ERR_CALLBACK,
    SC_ERR_NOT_COVER,
    SC_ERR_NOT_PRIME_COVER,
    SC_ERR_NOT_DUAL_SOL,
    SC_ERR_PRIMAL,
    SC_ERR_DUAL,
    SC_ERR_DUAL_3,
    SC_ERR_CPXDUAL_0,
    SC_ERR_BALAS_COND_VIOLATED,
    SC_ERR_BALAS_BRANCH_RULE_1,
};

#endif // PARAMS_H
